/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author A.M
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jbtn_report = new javax.swing.JButton();
        jbtn_dashboard = new javax.swing.JButton();
        jbtn_user = new javax.swing.JButton();
        jbt_product = new javax.swing.JButton();
        jbtn_session = new javax.swing.JButton();
        jbtn_stock = new javax.swing.JButton();
        jbtn_order = new javax.swing.JButton();
        jbtn_setting = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jlabel_Name = new javax.swing.JLabel();
        jbtn_logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard = new javax.swing.JPanel();
        User = new javax.swing.JPanel();
        Products = new javax.swing.JPanel();
        Sessions = new javax.swing.JPanel();
        Stocks = new javax.swing.JPanel();
        Order = new javax.swing.JPanel();
        Settings = new javax.swing.JPanel();
        Reports = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Dashboard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        kGradientPanel1.setkEndColor(new java.awt.Color(32, 58, 67));
        kGradientPanel1.setkStartColor(new java.awt.Color(44, 83, 100));
        kGradientPanel1.setName(""); // NOI18N
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 50));

        jbtn_report.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_report.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_report.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Accounting_20px.png"))); // NOI18N
        jbtn_report.setText("Reports");
        jbtn_report.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_report.setIconTextGap(3);
        jbtn_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_reportMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbtn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 200, 40));

        jbtn_dashboard.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_dashboard.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Speed_20px.png"))); // NOI18N
        jbtn_dashboard.setText("Dashboard");
        jbtn_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_dashboard.setIconTextGap(3);
        jbtn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_dashboardMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbtn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 40));

        jbtn_user.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_user.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_user.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_20px.png"))); // NOI18N
        jbtn_user.setText("User");
        jbtn_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_user.setIconTextGap(3);
        jbtn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_userMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbtn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 40));

        jbt_product.setBackground(new java.awt.Color(0, 102, 102));
        jbt_product.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbt_product.setForeground(new java.awt.Color(255, 255, 255));
        jbt_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Product_20px.png"))); // NOI18N
        jbt_product.setText("Products");
        jbt_product.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbt_product.setIconTextGap(3);
        jbt_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbt_productMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbt_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 40));

        jbtn_session.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_session.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_session.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_session.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit_20px.png"))); // NOI18N
        jbtn_session.setText("Sessions");
        jbtn_session.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_session.setIconTextGap(3);
        jbtn_session.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_sessionMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbtn_session, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 40));

        jbtn_stock.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_stock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_stock.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Scan Stock_20px.png"))); // NOI18N
        jbtn_stock.setText("Sells Stock");
        jbtn_stock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_stock.setIconTextGap(3);
        jbtn_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_stockMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbtn_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 40));

        jbtn_order.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_order.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_order.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Speed_20px.png"))); // NOI18N
        jbtn_order.setText("Order");
        jbtn_order.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_order.setIconTextGap(3);
        jbtn_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_orderMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbtn_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 40));

        jbtn_setting.setBackground(new java.awt.Color(0, 102, 102));
        jbtn_setting.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_setting.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Settings_20px.png"))); // NOI18N
        jbtn_setting.setText("Setting");
        jbtn_setting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtn_setting.setIconTextGap(3);
        jbtn_setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_settingMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jbtn_setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, 40));

        kGradientPanel2.setkEndColor(new java.awt.Color(32, 58, 67));
        kGradientPanel2.setkStartColor(new java.awt.Color(44, 83, 100));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_Name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel_Name.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Name.setText("Andre Mugabo");
        kGradientPanel2.add(jlabel_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        jbtn_logout.setBackground(new java.awt.Color(0, 153, 153));
        jbtn_logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbtn_logout.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_logout.setText("Logout");
        kGradientPanel2.add(jbtn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 983, Short.MAX_VALUE)
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Dashboard);

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", User);

        javax.swing.GroupLayout ProductsLayout = new javax.swing.GroupLayout(Products);
        Products.setLayout(ProductsLayout);
        ProductsLayout.setHorizontalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        ProductsLayout.setVerticalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", Products);

        javax.swing.GroupLayout SessionsLayout = new javax.swing.GroupLayout(Sessions);
        Sessions.setLayout(SessionsLayout);
        SessionsLayout.setHorizontalGroup(
            SessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        SessionsLayout.setVerticalGroup(
            SessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", Sessions);

        javax.swing.GroupLayout StocksLayout = new javax.swing.GroupLayout(Stocks);
        Stocks.setLayout(StocksLayout);
        StocksLayout.setHorizontalGroup(
            StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        StocksLayout.setVerticalGroup(
            StocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", Stocks);

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", Order);

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab7", Settings);

        javax.swing.GroupLayout ReportsLayout = new javax.swing.GroupLayout(Reports);
        Reports.setLayout(ReportsLayout);
        ReportsLayout.setHorizontalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        ReportsLayout.setVerticalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab8", Reports);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        SessionHolder  getSession = new SessionHolder();
        jlabel_Name.setText(getSession.getUserName());
    }//GEN-LAST:event_formWindowOpened

    private void jbtn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_dashboardMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbtn_dashboardMouseClicked

    private void jbtn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_userMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jbtn_userMouseClicked

    private void jbt_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_productMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jbt_productMouseClicked

    private void jbtn_sessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_sessionMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jbtn_sessionMouseClicked

    private void jbtn_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_stockMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jbtn_stockMouseClicked

    private void jbtn_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_orderMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jbtn_orderMouseClicked

    private void jbtn_settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_settingMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jbtn_settingMouseClicked

    private void jbtn_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_reportMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_jbtn_reportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Order;
    private javax.swing.JPanel Products;
    private javax.swing.JPanel Reports;
    private javax.swing.JPanel Sessions;
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel Stocks;
    private javax.swing.JPanel User;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbt_product;
    private javax.swing.JButton jbtn_dashboard;
    private javax.swing.JButton jbtn_logout;
    private javax.swing.JButton jbtn_order;
    private javax.swing.JButton jbtn_report;
    private javax.swing.JButton jbtn_session;
    private javax.swing.JButton jbtn_setting;
    private javax.swing.JButton jbtn_stock;
    private javax.swing.JButton jbtn_user;
    private javax.swing.JLabel jlabel_Name;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
